language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "iojs"
before_install:
  - 'export CHROME_BIN=chromium-browser'
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm install jspm@0.16.15"
  - "node_modules/.bin/jspm config endpoints.github.auth $JSPM_GITHUB_AUTH_TOKEN"
  - "make install"
env:
  global:
  - secure: "YUagZnZjiJJg4Xqnav9WsgfslOkIWT9KytML4cCpkYCSPSYvL3AHWH2TfoJmJChnGfIMWnQEBEnTOrSlFf3muS6xKjrK3KGq8og5OCPslVAMsJBsPnUmK1iVIh3kcxqU+6HMycMAFCiAEowYQnm5Rq4KwOJb1leHrRZPjJLXwgZ/jUxWY2+D4P/9ycgSxy+vRzmFSKxSoxCaI9NoLSnWbMG2OM09+y2r1oXuScerMMaObR8BNDvGVZv8ypdlDSTQgkc8N4FvKypyYkmanACFWbEbo+Qv46e5xmV4KvIQBzEj1lJT5sMx5Jweg1qNN86ata4W5wMBfRWUpkymxjNhPkf+uzD79mDrlWMb3ur1jfRhSA8Gqjtk7bSjWCQdkzzjIRWaaQDeEjJChR7bRGlmmC8PA9cF4MndnpZS6aqgbBBYKwnz9K0WIG9sLccBd5Pi8AtgT3LmUh68sjXG1yN/U60++7RxBJjMt0IEU02okC0cGXl2p5PfWnPrABbSLdYwXefxnyBK/M0KqarUnpGtggalCecFL5nKdusnNoIrPGQ6ZR0iw+OXB02mmlRyoqwIambi9NTmAXoI3NJhD/oXZYKe98NzOv/hFRQZeF4LUPZ8Xbw9qpmK1VJopCFlbmZsuL6tN+ITjGhlJRlWrZQeWKJI/dUkzbO1i6OE8NtQick="
